### ISSUE TITLE
questions about image id = 1

### ISSUE THREAD

**Issue by xixiareone** [brandontrabucco/cider#1]
thanks for you great work I am interested in your work. But I have a question about your code in "image id = 1", Does this refer to the second sentence ？

**Comment by brandontrabucco** [comment]
Hi xixiareone,

Thanks for your interest in my code!  This repo was never quite completed, so I recommend using this excellent code-base for evaluating image captioning models: https://github.com/Maluuba/nlg-eval.

The image id refers to which training example a particular prediction corresponds to. In the `cider.py` there are 5 training examples, and the `candidate` sentence corresponds to training example 1.

-Brandon

**Comment by brandontrabucco** [comment]
Let me know how else I can help!

**Comment by xixiareone** [comment]
thanks you very much!
